# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='source',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
