# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_Response_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='Response',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
