# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_Response_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='Response',
            name='name',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
