# Generated by Django 2.0.2 on 2018-03-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_api_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API_message',
        ),
    ]
