# Generated by Django 2.0.2 on 2018-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_delete_api_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='error',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='success',
            field=models.TextField(blank=True, default='True', null=True),
        ),
    ]
