# Generated by Django 2.0.2 on 2018-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180314_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='error',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='success',
            field=models.NullBooleanField(default=True),
        ),
    ]
