# Generated by Django 2.0.2 on 2018-03-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0008_auto_20180314_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('reponse', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField(blank=True, default='None', null=True)),
                ('success', models.NullBooleanField(default=True)),
                ('error', models.TextField(blank=True, default='None', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=True)),
                ('current_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Tokens')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.AddField(
            model_name='discussion',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Users'),
        ),
    ]
