# Generated by Django 2.0.2 on 2018-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20180323_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='quickreplies',
            field=models.ManyToManyField(related_name='_reponse_quickreplies_+', to='bot.Reponse'),
        ),
    ]
