# Generated by Django 2.0.2 on 2018-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_reponse_quickreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='quickreplies',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
